spring.application.name=github-access-report

# ==============================
# Server Configuration
# ==============================
server.port=8080

# ==============================
# GitHub API Configuration
# ==============================
github.api-url=https://api.github.com
github.max-concurrent-requests=10

# ==============================
# Logging
# ==============================
logging.level.root=INFO
logging.level.com.ai.cloudEagle.githubreport=DEBUG

# ==============================
# Spring Cache Configuration
# ==============================
spring.cache.type=simple